### ISSUE TITLE
Dataset Importer Error

### ISSUE THREAD

**Issue by Julm** [texta-tk/texta#32]
Hi there and thanks for this great initiative! 

Unfortunately, I can't import any data.

When trying to do so on http://localhost:8000/dataset_importer/ (there is no explicit link to this page in the interface BTW), by 
choosing _simple documents_ or _archives_, 
selecting the appropriate file in _Input data_, 
naming the dataset, 
setting overwrite dataset or not,
the job is correctly submitted but processing does not happen. 

The following error being logged:

`[25/Jun/2018 15:26:04] "GET /static/base/img/bg.jpg HTTP/1.1" 200 34998
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 1351, in _after_fork
    thread._stop()
TypeError: 'Event' object is not callable
[25/Jun/2018 15:26:19] "POST /dataset_importer/import HTTP/1.1" 200 0
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/texta/dataset_importer/importer/importer.py", line 296, in _import_dataset
    parameter_dict['file_path'] = download(parameter_dict['url'], parameter_dict['directory'])
KeyError: 'url'
[25/Jun/2018 15:26:19] "GET /dataset_importer/reload_table HTTP/1.1" 200 4436`

**Comment by rsirel** [comment]
Hi and thanks for the input. We have confirmed it is a bug (sigh) and are currently investigating possible solutions. We hope to introduce a hotfix later this week.

**Comment by Julm** [comment]
Thank you! 

I run the docker container; shouldn't it pull all the dependencies it needs? 

I tried first to import a single PDF, then a ZIP archive containing a few PDFs.

**Comment by Julm** [comment]
I'm afraid I encounter the same error.

I pulled the repo and am up to date.
I removed all my docker images and containers.
And ran `$>/texta/docker-compose up -d`

**Comment by mrxkollo** [comment]
@Julm It appears the issue was caused by a faulty database connection to the postgresql instance. We reverted back to Djangos default sqlite and managed to successfully import data using PDF and ZIP files from our local instance.

We will investigate the details of the issue in our dev builds, until then the master branch will be using the working instance of sqllite.
