### ISSUE TITLE
django 2.0.2 doesn't seem to be available for python2.7

### ISSUE THREAD

**Issue by zwurgl** [texta-tk/texta#33]
Hi there, 
texta looks like a great package. Just when trying to install in in my python 2.7 virtual env on Ubuntu, pip informs me that there is no django 2.0.2 for python 2.7 although this is explicitly required in the requirements.txt

Would it make sens to try to run it with an earlier version? Or with python 3.5? Or what am I missing? 

Thanks for a hint and best regards,
Stefan

**Comment by rsirel** [comment]
Hi!
We no longer support Python 2.X. You should use at least Python 3.5 try the Docker version (which is the encouraged approach for new users): https://texta-tk.github.io/docker.html.

Cheers,
Raul
