### ISSUE TITLE
update docs: if in docker-compose elastic is looping in start-errror

### ISSUE THREAD

**Issue by hillar** [texta-tk/texta#34]
if elasticsearch will die after start with:

ERROR: [1] bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] 

one should fix it with something like:

sysctl -w vm.max_map_count=262144

----

 git clone https://github.com/texta-tk/texta.git
 cd texta/docker/
 docker-compose pull
 docker-compose up

----

Linux texta-test-2 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

----

texta-elastic | [2019-01-16T13:34:13,668][INFO ][o.e.d.DiscoveryModule    ] [TEXTA-1] using discovery type [zen]
texta-elastic | [2019-01-16T13:34:14,317][INFO ][o.e.n.Node               ] [TEXTA-1] initialized
texta-elastic | [2019-01-16T13:34:14,318][INFO ][o.e.n.Node               ] [TEXTA-1] starting ...
texta-elastic | [2019-01-16T13:34:14,512][INFO ][o.e.t.TransportService   ] [TEXTA-1] publish_address {192.168.16.2:9300}, bound_addresses {0.0.0.0:9300}
texta-elastic | [2019-01-16T13:34:14,527][INFO ][o.e.b.BootstrapChecks    ] [TEXTA-1] bound or publishing to a non-loopback address, enforcing bootstrap checks
texta-elastic | ERROR: [1] bootstrap checks failed
texta-elastic | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
texta-elastic | [2019-01-16T13:34:14,538][INFO ][o.e.n.Node               ] [TEXTA-1] stopping ...
texta-elastic | [2019-01-16T13:34:14,612][INFO ][o.e.n.Node               ] [TEXTA-1] stopped
texta-elastic | [2019-01-16T13:34:14,612][INFO ][o.e.n.Node               ] [TEXTA-1] closing ...
texta-elastic | [2019-01-16T13:34:14,627][INFO ][o.e.n.Node               ] [TEXTA-1] closed
texta-elastic exited with code 78

**Comment by rsirel** [comment]
This is a Linux-related thing. When running Elasticsearch inside Docker, one is required to increase the vm.max_map_count paramater on the host machine:

`sysctl -w vm.max_map_count=262144`

Check this for further reading: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
