### ISSUE TITLE
Error training language model

### ISSUE THREAD

**Issue by andopaju** [texta-tk/texta#35]
Training language model results in traceback:
```
  File "   /texta/task_manager/tasks/workers/language_model_worker.py", line 50, in run
    iter=int(num_passes)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 633, in __init__
    end_alpha=self.min_alpha, compute_loss=compute_loss)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/word2vec.py", line 856, in train
    queue_factor=queue_factor, report_delay=report_delay, compute_loss=compute_loss, callbacks=callbacks)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 938, in train
    queue_factor=queue_factor, report_delay=report_delay, compute_loss=compute_loss, callbacks=callbacks)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 421, in train
    total_words=total_words, **kwargs)
  File "   /anaconda3/envs/texta-toolkit/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 1044, in _check_training_sanity
    raise RuntimeError("you must first build vocabulary before training the model")
```

Debugging reveals it might be caused by data that is discarded in EsIterator?
First 
`response = self.es_m.scroll()`
 is called
then, another scroll is called overwriting results obtained previously.
`response = self.es_m.scroll(scroll_id=scroll_id)`
https://github.com/texta-tk/texta/blob/master/task_manager/tools/data_manager.py#L75-L83

To reproduce - add dataset with less than ES_SCROLL_SIZE rows.

**Comment by rsirel** [comment]
How many documents do you have in your dataset? This is a symptom of having too few documents to build the Word2Vec model.

**Comment by andopaju** [comment]
It's true that the error came up while testing with one document only.
But the cause seems to be that first ES_SCROLL_SIZE rows are discarded altogether and not taken into account while training.

**Comment by andopaju** [comment]
Can't reproduce anymore, most likely false alert

**Comment by andopaju** [comment]
Nope, it is definitely a bug.
If I comment out these lines:

```
#response = self.es_m.scroll(scroll_id=scroll_id)
#scroll_id = response['_scroll_id']
```

and then put
```
total_hits = 0
```

then training is completed successfully.

first response (before while loop):
{"_scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAYoFklGcnVXVE8wUlBTb0h4bnNJcnBaZlEAAAAAAAAGKxZJRnJ1V1RPMFJQU29IeG5zSXJwWmZRAAAAAAAABioWSUZydVdUTzBSUFNvSHhuc0lycFpmUQAAAAAAAAYsFklGcnVXVE8wUlBTb0h4bnNJcnBaZlEAAAAAAAAGKRZJRnJ1V1RPMFJQU29IeG5zSXJwWmZR", "_shards": {"total": 5, "skipped": 0, "successful": 5, "failed": 0}, "hits": {"total": 1, "max_score": 1.0, "hits": [{"_type": "ariseadustik", "_id": "3DrvvGgBLr6SwCRtWKxk", "_index": "ariseadustik", "_score": 1.0, "_source": {"text": "V\u00e4ljaandja: Riigikogu\nAkti liik: seadus\n...

second response - now inside while loop (notice no hits):
{"_scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAYoFklGcnVXVE8wUlBTb0h4bnNJcnBaZlEAAAAAAAAGKxZJRnJ1V1RPMFJQU29IeG5zSXJwWmZRAAAAAAAABioWSUZydVdUTzBSUFNvSHhuc0lycFpmUQAAAAAAAAYsFklGcnVXVE8wUlBTb0h4bnNJcnBaZlEAAAAAAAAGKRZJRnJ1V1RPMFJQU29IeG5zSXJwWmZR", "_shards": {"total": 5, "skipped": 0, "successful": 5, "failed": 0}, "hits": {"total": 1, "max_score": 1.0, "hits": []}, "timed_out": false, "took": 1}}



Attached example datafile.
[120122018002.txt](https://github.com/texta-tk/texta/files/2844203/120122018002.txt)

**Comment by ranetp** [comment]
This should now be fixed, but make sure that "Frequency threshold", in the parameters you choose when starting a Language Model Task, is low enough to fit your dataset
